name: Agda Action CI

on:
  push:
    branches:
      - main
    paths:
      - "agda/**"
  pull_request:
    paths:
      - "agda/**"
  workflow_dispatch:

jobs:

  agda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: wenkokke/setup-agda@v2
        with:
          agda-version: '2.6.4.3'
          agda-stdlib-version: '2.1'
      - run: agda plfa/part1/Naturals.lagda.md
        working-directory: ./agda
